name: Lint

on: [push]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install -g eslint
      - run: npx eslint --init
      - run: npx eslint task5-scm-worker.js
      - uses: stefanoeb/eslint-action@1.0.2

